--- #YAML:1.0
name:                App-BCVI-NotifyDesktop
version:             1.00
abstract:            Display a notification message at the user's desktop
license:             ~
author:              
    - Grant McLean <grantm@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Desktop::Notify:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
